# Generated by Django 3.0.5 on 2020-06-20 20:30

from django.db import migrations, models
import face.models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfaceimage',
            name='image',
            field=models.ImageField(upload_to=face.models.content_file_name),
        ),
    ]
